### ISSUE TITLE
Henry's Todo

### ISSUE THREAD

**Issue by henknopf** [ds-civic-data/big-pipe#2]
- [ ]  Gather data from Johnson Creek Watershed
- [ ] Find other important information on Willamette contaminants data
- [ ] Upload data to github page
- [ ] Determine how to deal with importing, tidying, and aggregating data
